
const tableName = "user"


await connection.execute(`begin execute immediate 'drop table ${tableName}';
exception when others then 
if sqlcode <> -942 then raise; 
end if;
end;`
);

await connection.execute(`create table ${tableName} (
id NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1),
name varchar2(4000),
creation_ts timestamp with time zone default current_timestamp,
gender varchar2(4000),
age NUMBER DEFAULT 21,
isMerried varchar2(10),
primary key (id))`
);